<?php

namespace Polcode\WhenBusArrivesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Polcode\WhenBusArrivesBundle\Entity\Arrival;
use Polcode\WhenBusArrivesBundle\Entity\Timetable;
use Polcode\WhenBusArrivesBundle\Entity\BusStop;

/**
 * ArrivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivalRepository extends EntityRepository {

    public function getByBusStopAndTimetableType($busStopId, $timetableType) {

        $query = $this->getAllByBusStopAndTimetableTypeQuery($busStopId, $timetableType);
        return $query->getResult();
    }

    private function getAllByBusStopAndTimetableTypeQuery($busStopId, $timetableType) {
        $query = $this->_em->createQuery('SELECT a FROM Polcode\WhenBusArrivesBundle\Entity\Arrival a'
                . ' JOIN a.timetable t '
                . 'JOIN t.busStop b  '
                . 'WHERE b.id = ' . $busStopId
                . ' AND t.type = ' . $timetableType);
        return $query;
    }

    public function getNearestByBusStopAndTimetableType($busStopId, $timetableType, $limit = 10) {
        $query = $this->_em->createQuery('SELECT a FROM Polcode\WhenBusArrivesBundle\Entity\Arrival a'
                . ' JOIN a.timetable t '
                . 'JOIN t.busStop b  '
                . 'WHERE b.id = ' . $busStopId
                . ' AND t.type = ' . $timetableType
                . ' AND a.time >= ' .date('His')
                . ' ORDER BY a.time');
        $query->setMaxResults($limit);
        return $query->getResult();
    }

}
