<?php

namespace Polcode\WhenBusArrivesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Polcode\WhenBusArrivesBundle\Entity\BusLine;

/**
 * BusLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusLineRepository extends EntityRepository {

    private static $instance = null;

    /**
     * 
     * @return BusLineRepository
     */
    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     *
     * @var BusLine[][]
     */
    private $busLines;
    private $sectionNumber = 0;

    public function __construct() {
        $this->busLines[0] = array();
    }

    public function findOrCreate($name, $direction) {
        for ($i = 0; $i < $this->sectionNumber; $i++) {
            foreach ($this->busLines[$i] as $oneBusLine) {
                if ($oneBusLine->getName() === $name && $oneBusLine->getDirection() === $direction) {
                    return $oneBusLine;
                }
            }
        }

        return $this->createInCurrentSection($name, $direction);
    }
    
    private function createInCurrentSection($name, $direction) {
        $newBusLine = new BusLine();
        $newBusLine->setName($name);
        $newBusLine->setDirection($direction);
        $this->busLines[$this->sectionNumber][] = $newBusLine;
        return $newBusLine;
    }
    
    public function createNewSection() {
        $this->sectionNumber++;
    }
    
    public function findInOtherSectionsOrCreateCurrentSection($name, $direction) {
        for ($i = 0; $i < $this->sectionNumber-1; $i++) {
            foreach ($this->busLines[$i] as $oneBusLine) {
                if ($oneBusLine->getName() === $name && $oneBusLine->getDirection() === $direction) {
                    return $oneBusLine;
                }
            }
        }
        
        return $this->createInCurrentSection($name, $direction);
    }
}
