Polcode\WhenBusArrivesBundle\Entity\BusLine:
    type: entity
    repositoryClass: Polcode\WhenBusArrivesBundle\Repository\BusLineRepository
    table: busLines
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        direction:
            type: string
            length: 255
    oneToMany:
        timetables:
            targetEntity: Timetable
            mappedBy: busLine
    manyToMany:
        busStops:
            targetEntity: BusStop
            mappedBy: busLines