Polcode\WhenBusArrivesBundle\Entity\BusStop:
    type: entity
    repositoryClass: Polcode\WhenBusArrivesBundle\Repository\BusStopRepository
    table: busStops
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: 255
    oneToMany:
        timetables:
            targetEntity: Timetable
            mappedBy: busStop
    manyToOne:
        community:
            targetEntity: Community
            inversedBy: busStops
            joinColumn:
                name: communityId
                referencedColumnName: id
    manyToMany:
        busLines:
            targetEntity: BusLine
            inversesBy: busStops
            joinTable:
                name: busStops_busLines
                joinColumns:
                    busStopId: 
                        referencedColumnName: id
                inverseJoinColumns:
                    busLineId:
                        referencedColumnName: id