Polcode\WhenBusArrivesBundle\Entity\Community:
    type: entity
    table: communities
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: 255
    oneToMany:
        busStops:
            targetEntity: BusStop
            mappedBy: community
    